### ISSUE TITLE
Faling build of hollow torus solid

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#1090]
## Describe the bug

I am trying to build a hollowed torus of radii `a_in` and `a_out` and major radius `R_0` by making a two concentring circular wires in the xz plane, get the corresonding hollowed face and revolve it by 360.0 degree.

I get some unexpected error

## Steps to reproduce

Simply run the following function

``` python
from bluemira.base.components import Component, PhysicalComponent
from bluemira.geometry.face import BluemiraFace
from bluemira.geometry.tools import make_circle, revolve_shape, wire_closure

def make_torus(a_in: float, a_out: float, R_0: float) -> PhysicalComponent:
    """
    create a Physical component containing a hollowed torus geometry
    of major radius R_0 and inner and outer minor radius a_1 and a_2
    respectively
    """
    # Make (open) initial wire
    inner_circle = make_circle(
        radius=a_in,
        center=(R_0, 0.0, 0.0),
        axis=(0.0, 1.0, 0.0),
        label="in_torus"
    )
    outer_circle = make_circle(
        radius=a_out,
        center=(R_0, 0.0, 0.0),
        axis=(0.0, 1.0, 0.0),
        label="out_torus"
    )

    # # close initial circles
    # inner_circle = wire_closure(inner_circle, label="in_torus")
    # outer_circle = wire_closure(outer_circle, label="out_torus")
    # print("DONKEY")

    # Make the face
    face = BluemiraFace([outer_circle, inner_circle], label="face")
    torus = revolve_shape(shape=face, degree=360.0)
    
    return PhysicalComponent("Little torus", torus)
```

## Expected behaviour

A nice torus component

## Screenshots / Tracebacks

``` bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skahn/codes/step/step-blueprint-reactor-design/tests/test_builder_tools.py", line 38, in make_torus
    return PhysicalComponent("Little torus", torus)
  File "/home/skahn/codes/bluemira/bluemira/geometry/tools.py", line 464, in wire_closure
    closure = BluemiraWire(cadapi.wire_closure(wire), label=label)
  File "/home/skahn/codes/bluemira/bluemira/geometry/wire.py", line 65, in __init__
    super().__init__(boundary, label, boundary_classes)
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 97, in __init__
    self.boundary = boundary
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 146, in boundary
    self._boundary = self._check_boundary(objs)
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 133, in _check_boundary
    raise TypeError(
TypeError: Only [<class 'bluemira.geometry.wire.BluemiraWire'>, <class 'Part.Wire'>] objects can be used for <class 'bluemira.geometry.wire.BluemiraWire'>
```

Trying to close the wires, I get using `wire_close`, I get 

``` bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skahn/codes/step/step-blueprint-reactor-design/tests/test_builder_tools.py", line 30, in make_torus
    inner_circle = wire_closure(inner_circle, label="in_torus")
  File "/home/skahn/codes/bluemira/bluemira/geometry/tools.py", line 464, in wire_closure
    closure = BluemiraWire(cadapi.wire_closure(wire), label=label)
  File "/home/skahn/codes/bluemira/bluemira/geometry/wire.py", line 65, in __init__
    super().__init__(boundary, label, boundary_classes)
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 97, in __init__
    self.boundary = boundary
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 146, in boundary
    self._boundary = self._check_boundary(objs)
  File "/home/skahn/codes/bluemira/bluemira/geometry/base.py", line 133, in _check_boundary
    raise TypeError(
TypeError: Only [<class 'bluemira.geometry.wire.BluemiraWire'>, <class 'Part.Wire'>] objects can be used for <class 'bluemira.geometry.wire.BluemiraWire'>
```

**Comment by je-cook** [comment]
I got it working with the below:

```
R_0 = 10
a_out = 9
a_in = 8
```
and setting the degree for the revolve to `359.9`
