### ISSUE TITLE
PsiConstraint currently incompatible with x and z np.arrays

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#1285]
## Describe the bug

When arrays are used to define the `x` and the `z` of the flux points used in `PsiConstraint` a matrix operation dimension error appears.

## Steps to reproduce

Use an array of points for the `PsiConstraint` and run an equilibrium optimization.

## Expected behaviour

No errors and an optimization that happends (but may fail for other reasons :D)

## Screenshots / Tracebacks

error traceback:

``` bash
Traceback (most recent call last):
  File "equilibrium_standalone.py", line 141, in <module>
    equilibrium, FoM_constraints = FBE_solver(
  File "/home/skahn/codes/step/step-blueprint-reactor-design/step_reactor/fbe_func.py", line 175, in FBE_solver
    iterator()
  File "/home/skahn/codes/bluemira/bluemira/equilibria/solve.py", line 495, in __call__
    iterator = iter(self)
  File "/home/skahn/codes/bluemira/bluemira/equilibria/solve.py", line 519, in __iter__
    self._setup()
  File "/home/skahn/codes/bluemira/bluemira/equilibria/solve.py", line 612, in _setup
    self._initial_optimise_coilset()
  File "/home/skahn/codes/bluemira/bluemira/equilibria/solve.py", line 606, in _initial_optimise_coilset
    self._optimise_coilset(**kwargs)
  File "/home/skahn/codes/bluemira/bluemira/equilibria/solve.py", line 461, in _optimise_coilset
    coilset = self.opt_prob.optimise(self.fixed_coils)
  File "/home/skahn/codes/bluemira/bluemira/equilibria/opt_problems.py", line 809, in optimise
    currents = self.opt.optimise(initial_currents)
  File "/home/skahn/codes/bluemira/bluemira/utilities/optimiser.py", line 133, in optimise
    x_star = super().optimise(x0)
  File "/home/skahn/codes/bluemira/bluemira/codes/_nlopt_api.py", line 430, in optimise
    x_star = self._opt.optimize(x0)
  File "/home/skahn/miniforge3/envs/bluemira/lib/python3.8/site-packages/nlopt/nlopt.py", line 334, in optimize
    return _nlopt.opt_optimize(self, *args)
  File "/home/skahn/codes/bluemira/bluemira/utilities/opt_problems.py", line 71, in __call__
    return self._f_constraint(constraint, vector, grad, **self._args)
  File "/home/skahn/codes/bluemira/bluemira/equilibria/opt_constraint_funcs.py", line 98, in Ax_b_constraint
    constraint[:] = np.dot(a_mat, scale * vector) - b_vec - value
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (7,2) and (7,) not aligned: 2 (dim 1) != 7 (dim 0)
```

## Propose solution 

See PR xxx

**Comment by je-cook** [comment]
Covered in #1963
