### ISSUE TITLE
Error when trying to retrieve curved faces from `BluemiraGeo`.

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#2037]
## Describe the bug

I cannot retrieve `BluemiraFace`s from higher Matryoshka `BluemiraGeo` objects for anything with a face that is not planar (it seems).

## Steps to reproduce

```python
    from bluemira.geometry.tools import make_circle, make_ellipse, make_bezier, extrude_shape

    circle = BluemiraFace(make_circle(axis=(0, 0, 1)))
    cylinder = extrude_shape(circle, (0, 0, 10))
    print(cylinder.is_valid())  # True

    ellipse = BluemiraFace(make_ellipse())
    ellipsinder = extrude_shape(ellipse, (10, 10, 10))
    print(ellipsinder.is_valid())  # True

    bezier = BluemiraFace(make_bezier(points=[(0, 0,0 ), (3, 0,1 ), (2, 0, 3), (0.5, 0, 0.4)], closed=True))
    beziender = extrude_shape(bezier, (0, 10, 0))
    print(beziender.is_valid())  # True
```
so far, so good, but when accessing the property below, an error occurs:

```python
>>> s.faces
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matti/code/bluemira/bluemira/geometry/shell.py", line 106, in faces
    return tuple([BluemiraFace(o) for o in cadapi.faces(self.shape)])
  File "/home/matti/code/bluemira/bluemira/geometry/shell.py", line 106, in <listcomp>
    return tuple([BluemiraFace(o) for o in cadapi.faces(self.shape)])
  File "/home/matti/code/bluemira/bluemira/geometry/face.py", line 50, in __init__
    super().__init__(boundary, label, boundary_classes)
  File "/home/matti/code/bluemira/bluemira/geometry/base.py", line 103, in __init__
    self._set_boundary(boundary)
  File "/home/matti/code/bluemira/bluemira/geometry/base.py", line 158, in _set_boundary
    self._boundary = self._check_boundary(objs)
  File "/home/matti/code/bluemira/bluemira/geometry/face.py", line 96, in _check_boundary
    raise TypeError(
TypeError: Only [<class 'bluemira.geometry.wire.BluemiraWire'>] objects can be used for <class 'bluemira.geometry.face.BluemiraFace'>

```

Note that the underlying objects do not complain and I can use them as normal:

```python
all([f.isValid() for f in ellipsinder.shape.Faces])  # True
```

## Environment (please complete the following information)

- OS: Ubuntu 20.04
- Version: 1.2.0
- Branch: develop

**Comment by CoronelBuendia** [comment]
@ivanmaione  FYI
