### ISSUE TITLE
PROCESS install script raises error

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#838]
## Describe the bug

I can't seem to install PROCESS with `bash scripts/install-process.sh`. I see this with v 2.2.0 and v 2.3.0.

## Steps to reproduce

Steps to reproduce the behaviour:

Run command: `bash scripts/install-process.sh` in bluemira folder

```bash
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dvds8go4/pathlib_e5d4cf83b8cd420ea7dcca44ba863735/setup.py", line 6, in <module>
          setup(
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/dist.py", line 457, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
          dist.entry_points for dist in unique(distributions())
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/home/matti/miniforge3/envs/bluemira-process-build/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
      AttributeError: 'PosixPath' object has no attribute 'read_text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
## Expected behaviour

I expect to be able to install PROCESS using this script.

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: e.g. Ubuntu 18.04
- Version [e.g. 0.0.x]
- Branch develop

## Additional context

I've narrowed it down to just `pip install pathlib >=1.0.1`. Which fails with the error above on python 3.8.12 (which we're loading into in the bluemira-process-build). It seems pathlib is not maintained any more?

**Comment by je-cook** [comment]
It seems like a very old dependency. Even on the [pypi page](https://pypi.org/project/pathlib/) it says to use [pathlib 2](https://pypi.org/project/pathlib2/). This strikes me a something PROCESS needs to fix, I'll pass it on up the chain. Its not even needed for current Python versions...

**Comment by je-cook** [comment]
actually this could stem from an old process dir, we dont `git pull` in the script if the process folder exists
