### ISSUE TITLE
`serialize_shape` / `deserialize_shape` not working for `TripleArc`

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#965]
## Describe the bug

Deserialisation of a serialised TripleArc wire does not work.

## Steps to reproduce

```python
from bluemira.geometry.tools import serialize_shape, deserialize_shape
from bluemira.geometry.parameterisations import TripleArc

t = TripleArc().create_shape()
data = serialize_shape(t)
new = deserialize_shape(data)
```

any call to new will fail when the wire is reconstructed.

## Expected behaviour

I expect the wire to be reconstructed properly and be approximately identical.

## Screenshots / Tracebacks

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matti/code/bluemira/bluemira/geometry/base.py", line 275, in __repr__
    new.append(f" length: {self.length}")
  File "/home/matti/code/bluemira/bluemira/geometry/base.py", line 162, in length
    return cadapi.length(self._shape)
  File "/home/matti/code/bluemira/bluemira/geometry/wire.py", line 96, in _shape
    return self._create_wire()
  File "/home/matti/code/bluemira/bluemira/geometry/wire.py", line 99, in _create_wire
    wire = apiWire(self._wires)
Part.OCCError: BRep_API: command not done

```

## Environment (please complete the following information)

- OS:  Ubuntu 18.04
- Version [e.g. 0.0.x]
- Branch #964 

## Additional context
It's possible this is related to `make_circle_arc_3P` (a different method to construct an `ArcOfCircle`) but I can't understand why the reconstruction would be any different. Also could be related to orientation issues, which we've seen before and can often cause these generic `command not done` errors.

**Comment by CoronelBuendia** [comment]
I've narrowed this done to the two different constructors we have for circle arcs; `make_circle` and `make_circle_arc_3P`.

The problem is that when you used `make_circle_arc_3P`, the underlying Curve has a Rotation, which is transferable to the reconstruction function `make_circle`.

```python
from bluemira.codes._freecadapi import make_circle, make_circle_arc_3P

ca_3P = make_circle_arc_3P([1, 0, 2], [2, 0, 3], [0, 0, 3.2])
ca_3P_e = ca_3P.Edges[0]
ca_3P_c = ca_3P_e.Curve

print("Original circle arc by 3 points")
print(ca_3P_e.FirstParameter)
print(ca_3P_e.LastParameter)

print(ca_3P_c.Radius)
print(ca_3P_c.Center)
print(ca_3P_c.Axis)

ca_r = make_circle(ca_3P_c.Radius, ca_3P_c.Center, ca_3P_e.FirstParameter, ca_3P_e.LastParameter, axis=ca_3P_c.Axis)
ca_r_e = ca_r.Edges[0]
ca_r_c = ca_r_e.Curve

print("Reconstructed circle arc")
print(ca_r_e.FirstParameter)
print(ca_r_e.LastParameter)

print(ca_r_c.Radius)
print(ca_r_c.Center)
print(ca_r_c.Axis)


print(ca_3P_c.Rotation)
print(ca_r_c.Rotation)
```

```
Original circle arc by 3 points
0.0
4.513051675402366
1.0091318583009936
Vector (0.9909090909090909, 0.0, 3.0090909090909093)
Vector (0.0, -1.0, 0.0)

Reconstructed circle arc
0.0
0.07876761104841767
1.0091318583009936
Vector (0.9909090909090909, 0.0, 3.0090909090909093)
Vector (0.0, -1.0, 0.0)

Rotation (0.502247111349476, 0.4977427439361695, -0.4977427439361695, 0.502247111349476)
Rotation (0.7071067811865476, 0.0, 0.0, 0.7071067811865476)
```
